### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by andocromn** [midwan/MB_SubSonic#19]
I regularly see that tracks have been skipped.  i checked the error log i found this.  feel free to contact me, thank you

12/13/2016 2:40:23 PM - 6.1.7601.65536 - 3.0.6067.36587 - url: Subsonic:\Artist-Albums\Aversions Crown\2011 - Servitude\Aversions Crown - 05 - Repurposed - Reprogrammed.mp3
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at MusicBeePlugin.Subsonic.GetFolderId(String url)
   at MusicBeePlugin.Subsonic.GetFileId(String url)
   at MusicBeePlugin.Subsonic.GetStream(String url)
   at MusicBeePlugin.Plugin.GetStream(String url)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at MusicBee.Plugin.#=qPq8KyXNNfUxSXUrCJ2GN9KbXBXru0nDLJUR5Ilf$N4k=(String #=qjkXI9lfX9ObP0F86RBxqRw==)
   at #=qk6b2Ov6eJoetXhtSbsoJza8WyvkqHciQhulLIGl7f3s=.#=q_I7c_puOW1yvvKf0jLqZUg==(#=qKozuzC721wnfP3yjuTMOvw== #=qS$LxADGeWOkanb8nMZ4qLg==)
   at #=qLJCihXCZZEJp22ze$qgSYJsUf_0ABlpFsDkdj_jGPDQ=.#=qtLFLYU$CDHsyHVEaxmhL1Q==(#=qfYPOrJe7iiJL8a6ogDB9Mg== #=qp49hY8SEBIgxTjFZr5vBVQ==, #=qFVQO4m8Q3K5g9T65fnIQ4qi4vNctK7t5bL4xu6JEjKQ= #=qypwTRWqlYwkKeZZikERCHQ==, Boolean #=qkkqmlo5e8FwSzpUe0_QeHA==, Boolean #=qeYj71Uk$B1IkG_qXFycLSQ==, Boolean #=qbD_C36NXoyxScpOGNeIkKD9RS3QtCxq1AkQJQwbBqds=, Boolean #=qwVmPCYpr5Bs3GLZc_CEK9Q==, Int32 #=qfjnZmNvrbseuPcYutx89OwGHMVmzPBMv$xUUdPa82U8=)
   at #=qLJCihXCZZEJp22ze$qgSYJsUf_0ABlpFsDkdj_jGPDQ=.#=q0NxX$ukx3Zr529oILODZ0A==(Object #=qgk8BCIMqxdWbbhr3pDKYmQ==)

**Comment by midwan** [comment]
Thanks for reporting this, I'll look into it.

**Comment by midwan** [comment]
@andocromn 
Do you still get this with the latest version? I have an idea what might be causing it and I was going to rewrite the area that may be responsible for this anyway, but I was curious if it's still happening from time to time.

**Comment by andocromn** [comment]
@midwan to be honest i have been troubleshooting with different versions so much that I can't be sure what versions i was using when i experienced this.  I believe it was MusicBee version 3_0_update2 and v2.2 of the subsonic plugin, from my notes and file history this was what I originally using when I started using MusicBee on Oct-6 2016.  It worked perfectly for a while, then I upgraded to MB update3 and started having problems.  I gone as far as trying to clear everything and revert to the original versions from Oct-6 but still have issues.

For Sanity purposes while troubleshooting I will be sticking to the newest versions from here on out.  I'm currently running MB v3.0.6132 with v2.9 of the Subsonic plugin.  The prevalent and reproducible issue I currently experience is that whenever I drag a track from Subsonic into the playing tracks it is unable to play the file i added to the queue and produces the message below in the error log

``
2/22/2017 10:48:02 AM - 10.0.14393.0 - 3.0.6132.15853 - System.NullReferenceException: Object reference not set to an instance of an object.
   at MusicBee.MusicBeeMain.#=qmw6gXBADHDwaj56Ko3_JLB5sGfysEpfMPjs0DNEVuSA=._Lambda$__1()

2/22/2017 10:55:01 AM - 10.0.14393.0 - 3.0.6132.15853 - url: Subsonic:\Lamb Of God/2006 - Sacrament/Lamb Of God - 01 - Walk With Me In Hell.mp3\Lamb Of God\2006 - Sacrament\Lamb Of God - 01 - Walk With Me In Hell.mp3
System.IO.FileNotFoundException: Unable to find the specified file.
   at #=qL2UZEcvMrPitgReDO3HbSgdypFfX_8TMfrXivfOsZtI=.#=qGQC_2o9Q5sZ9bkzuAKP65w==(#=qZsbih$YwvJ5OgcdcG81xQg== #=qJUxXiyd3fKZJQzTV3u9E1Q==, #=qI_C_6$a81pAebbaYnO7VwtLwgieay75o4_nnJJNNjuc= #=qWNEajmyquudIW8ofKsTsYw==, Boolean #=qfXs3HYh95yMKW4A03MtoNw==, Boolean #=qYs2Z6UwWi2c8xan9u90i7Q==, Boolean #=qW_1SBa15KDNcwqSjJ8CjkKy0xdpWGG4_icDEloyt0YA=, Boolean #=qx3l6wHqqNyxPLhx6yQ9A7g==, Int32 #=qdVu9os5zbCfLiiWxwl9Wf26fSqcmhm8bAdrWpZC7RoI=)
   at #=qL2UZEcvMrPitgReDO3HbSgdypFfX_8TMfrXivfOsZtI=.#=qbfludmPPl53g5kMHMTqovQ==(Object #=qsM$WObGdzVdE22zJ22ekag==)
``

I believe your credentials to my subsonic server are still valid, let me know if you need anything else

and thanks again btw

**Comment by midwan** [comment]
@andocromn 
OK, let's handle this in a separate issue then - https://github.com/midwan/MB_SubSonic/issues/23

I'll close this one.
