### ISSUE TITLE
Server did not respond as expected with Airsonic.

### ISSUE THREAD

**Issue by zeknurn** [midwan/MB_SubSonic#28]
I'm running Airsonic in a docker and from what I can tell the Subsonic Client should work just fine.  But I'm getting "The Subsonic server did not respond as expected, do you want to save anyway?"

Latest version of MusicBee on Windows, tried both the standalone installer and the Windows Store version. 
Protocol HTTP
Local IP and the correct port.
Default path
Tried both Auth
Username and password as configured.

Same IP,Port and login works just fine in Dsub. 

This is what I get in the MusicBee error log if I force save and try to access "Subsonic"

`2017-12-30 14:17:14 - 10.0.16299.0 - 3.1.6512.37408 - System.NullReferenceException: Object reference not set to an instance of an object.
   at MusicBee.MusicBeeMain.#=qMqgii23tmGCxQkQ7r3cJpcp4gjniALEIL1elu02Mik8=._Lambda$__0()

2017-12-30 14:17:18 - 10.0.16299.0 - 3.1.6512.37408 - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at MusicBeePlugin.Subsonic.GetFolders(String path)
   at MusicBeePlugin.Plugin.GetFolders(String path)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at MusicBee.Plugin.#=qQUpUn5N8lYkFPCtXQu7Mef5QTU_oXhPhAWifZZtz0Ks=(#=q41NzncEMO8SDJEOTqDnjcaH2$oGkWqNpRJ8AQa6xdlU= #=qLPUdbirBef4hX89UQG9hxQ==)
   at #=qzug4240qG$g9_iZh5UO5XddRrIYrofwznvLjcgwQfVQ=.#=qVBeVawXQCiIYeYsaJASOdA==(#=q41NzncEMO8SDJEOTqDnjcaH2$oGkWqNpRJ8AQa6xdlU= #=qLrMSn0hK2ktM6yhlvOpSwQ==)
   at #=qNCuO9rzXAuEKWjmDfHrDJBNxr8OvO3w5KaDpmNXNGYA=.#=qfVYRKrk0S4EF2ywkw9MwEA==()
   at #=qKnoHtp0YzG1FUVUvcj0okz$Wa5XCBjKegKFd$0EqgWQ=.#=q6VVmz3SNEkznSq_cmFOZQsNYNi76JSPN3N7mjhGnn1I=(#=qrnfJtek5RJwHJjicTp8jiA== #=qd$RJQoh850Bx4WHznAWrYw==)`

**Comment by midwan** [comment]
@zeknurn 
The exception you posted above mentions that it can't find/open a .dll (RestSharp.dll) that is supposed to be bundled together with the plugin, did you place it in the same folder together?

**Comment by zeknurn** [comment]
@midwan Yeah, it looks that was the problem. I did another reinstall of MusicBee and extracted a new set of plugin files this time in \AppData\Roaming\MusicBee\Plugins just to try to see if it would work and it did.

I have also since then tried moving the plugin files back to Program Files (x86)\MusicBee\Plugins and it now works there too. 

I don't know what caused it but you can close and delete this issue. Thank you for the help.

**Comment by midwan** [comment]
@zeknurn Thanks for confirming! :)
